CREATE TABLE #TempSubjectss
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [CourseName] INT NOT NULL,
    [SpecialtyName] NVARCHAR(50) NOT NULL
)

INSERT INTO #TempSubjectss
(ID, [Name], CourseName, [SpecialtyName])
VALUES
(NEWID(), '1', 1, 'Economy'),
(NEWID(), '2', 1, 'Economy'),
(NEWID(), '3', 1, 'Economy'),
(NEWID(), '4', 1, 'Economy'),
(NEWID(), '5', 1, 'Economy'),
(NEWID(), '6', 1, 'Psychology'),
(NEWID(), '7', 1, 'Psychology'),
(NEWID(), '8', 1, 'Psychology'),
(NEWID(), '9', 1, 'Psychology'),
(NEWID(), '10', 1, 'Psychology'),
(NEWID(), '11', 1, 'Journalism'),
(NEWID(), '12', 1, 'Journalism'),
(NEWID(), '13', 1, 'Journalism'),
(NEWID(), '14', 1, 'Journalism'),
(NEWID(), '15', 1, 'Journalism'),
(NEWID(), '16', 2, 'Economy'),
(NEWID(), '17', 2, 'Economy'),
(NEWID(), '18', 2, 'Economy'),
(NEWID(), '19', 2, 'Economy'),
(NEWID(), '20', 2, 'Economy'),
(NEWID(), '21', 2, 'Psychology'),
(NEWID(), '22', 2, 'Psychology'),
(NEWID(), '23', 2, 'Psychology'),
(NEWID(), '24', 2, 'Psychology'),
(NEWID(), '25', 2, 'Psychology'),
(NEWID(), '26', 2, 'Journalism'),
(NEWID(), '27', 2, 'Journalism'),
(NEWID(), '28', 2, 'Journalism'),
(NEWID(), '29', 2, 'Journalism'),
(NEWID(), '30', 2, 'Journalism'),
(NEWID(), '31', 3, 'Economy'),
(NEWID(), '32', 3, 'Economy'),
(NEWID(), '33', 3, 'Economy'),
(NEWID(), '34', 3, 'Economy'),
(NEWID(), '35', 3, 'Economy'),
(NEWID(), '36', 3, 'Psychology'),
(NEWID(), '37', 3, 'Psychology'),
(NEWID(), '38', 3, 'Psychology'),
(NEWID(), '39', 3, 'Psychology'),
(NEWID(), '40', 3, 'Psychology'),
(NEWID(), '41', 3, 'Journalism'),
(NEWID(), '42', 3, 'Journalism'),
(NEWID(), '43', 3, 'Journalism'),
(NEWID(), '44', 3, 'Journalism'),
(NEWID(), '45', 3, 'Journalism'),
(NEWID(), '46', 4, 'Economy'),
(NEWID(), '47', 4, 'Economy'),
(NEWID(), '48', 4, 'Economy'),
(NEWID(), '49', 4, 'Economy'),
(NEWID(), '50', 4, 'Economy'),
(NEWID(), '51', 4, 'Psychology'),
(NEWID(), '52', 4, 'Psychology'),
(NEWID(), '53', 4, 'Psychology'),
(NEWID(), '54', 4, 'Psychology'),
(NEWID(), '55', 4, 'Psychology'),
(NEWID(), '56', 4, 'Journalism'),
(NEWID(), '57', 4, 'Journalism'),
(NEWID(), '58', 4, 'Journalism'),
(NEWID(), '59', 4, 'Journalism'),
(NEWID(), '60', 4, 'Journalism'),
(NEWID(), '61', 5, 'Economy'),
(NEWID(), '62', 5, 'Economy'),
(NEWID(), '63', 5, 'Economy'),
(NEWID(), '64', 5, 'Economy'),
(NEWID(), '65', 5, 'Economy'),
(NEWID(), '66', 5, 'Psychology'),
(NEWID(), '67', 5, 'Psychology'),
(NEWID(), '68', 5, 'Psychology'),
(NEWID(), '69', 5, 'Psychology'),
(NEWID(), '70', 5, 'Psychology'),
(NEWID(), '71', 5, 'Journalism'),
(NEWID(), '72', 5, 'Journalism'),
(NEWID(), '73', 5, 'Journalism'),
(NEWID(), '74', 5, 'Journalism'),
(NEWID(), '75', 5, 'Journalism'),
(NEWID(), '76', 6, 'Economy'),
(NEWID(), '77', 6, 'Economy'),
(NEWID(), '78', 6, 'Economy'),
(NEWID(), '79', 6, 'Economy'),
(NEWID(), '80', 6, 'Economy'),
(NEWID(), '81', 6, 'Psychology'),
(NEWID(), '82', 6, 'Psychology'),
(NEWID(), '83', 6, 'Psychology'),
(NEWID(), '84', 6, 'Psychology'),
(NEWID(), '85', 6, 'Psychology'),
(NEWID(), '86', 6, 'Journalism'),
(NEWID(), '87', 6, 'Journalism'),
(NEWID(), '88', 6, 'Journalism'),
(NEWID(), '89', 6, 'Journalism'),
(NEWID(), '90', 6, 'Journalism')

INSERT INTO [dbo].[Subject]
(ID, [Name], CourseID, SpecialtyId)
SELECT ts.Id, ts.[Name], c.Id, s.Id
FROM #TempSubjectss ts
JOIN [dbo].[Course] c ON c.Name = ts.CourseName 
JOIN [dbo].[Specialty] s ON s.Name = ts.SpecialtyName 