CREATE TABLE [dbo].[Score]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Value] INT NOT NULL, 
    [SubjectId] UNIQUEIDENTIFIER NOT NULL, 
    [StudentId] UNIQUEIDENTIFIER NOT NULL, 
    [CourseId] UNIQUEIDENTIFIER NOT NULL 
)
