CREATE TABLE [dbo].[Subject]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(50) NOT NULL, 
    [CourseId] UNIQUEIDENTIFIER NOT NULL, 
    [SpecialtyId] UNIQUEIDENTIFIER NOT NULL
)
